language: go

go:
  - "1.x"
  - master

services:
  - docker

before_install:
  - curl -LSso "${GOPATH}/bin/dep" https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64
  - chmod +x "${GOPATH}/bin/dep"

install:
  - dep ensure
  - .travis-ci/compile.sh

script: "true"
